language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-c' ]; then cd .. && eval "mv $currentfolder generator-c" && cd generator-c; fi

